// <auto-generated />
namespace Practico1v4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class populartablas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(populartablas));
        
        string IMigrationMetadata.Id
        {
            get { return "201804201852217_popular tablas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
