// <auto-generated />
namespace Practico1v4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class sacartelefono : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sacartelefono));
        
        string IMigrationMetadata.Id
        {
            get { return "201805311932205_sacar telefono"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
