// <auto-generated />
namespace Practico1v4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FKrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FKrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201804201850504_FK required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
