// <auto-generated />
namespace Practico1v4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class operacionymodifrol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(operacionymodifrol));
        
        string IMigrationMetadata.Id
        {
            get { return "201805292227584_operacion y modif rol"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
