// <auto-generated />
namespace Practico1v4.MigrationsTenants
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class agregocamposdeempresa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregocamposdeempresa));
        
        string IMigrationMetadata.Id
        {
            get { return "201808072002407_agrego campos de empresa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
