// <auto-generated />
namespace Practico1v4.MigrationsTenants
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ultimonrocomprobante : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ultimonrocomprobante));
        
        string IMigrationMetadata.Id
        {
            get { return "201810062017406_ultimonrocomprobante"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
